package com.vsulimov.logbookstatistic.model

/**
 * This model describes the report that will be generated by the program.
 * The report contains the following information: the year, the number of days with flights,
 * days when the number of flights is greater than 1, types of aircraft and their corresponding number of flights,
 * and total air time.
 */
data class Report(
    var year: String? = null,
    var uniqueDaysWithFlights: Int? = null,
    var daysWithMultipleFlights: Map<String, Int>? = null,
    var aircraftTypesCount: Map<String, Int>? = null,
    var totalFlightTime: String? = null
)
